<?php
/**
 * Implements hook_rules_action_info().
 */
function custom_rules_rules_action_info() {
    $actions['create_custom_user'] = array(
      'label' => t('Create custom user'),
      'group' => t('My custom actions'),
      'parameter' => array(
        // User login.
        'login' => array(
          'type' => 'text',
          'label' => t('Login'),
          'description' => t("The user's login."),
        ),
        // User password.
        'password' => array(
          'type' => 'text',
          'label' => t('Password'),
          'description' => t("The user's password."),
        ),
        // User email.
        'email' => array(
          'type' => 'text',
          'label' => t('Email'),
          'description' => t("The user's email."),
        ),
      ),
    );
    $actions['add_password'] = array(
      'label' => t('Generate a password'),
      'group' => t('My custom actions'),
      'parameter' => array(
        // Password's length.
        'length' => array(
          'type' => 'integer',
          'label' => t('Password lenght'),
          'description' => t('Password lenght'),
        ),
      ),
      'provides' => array(
        'password_added' => array(
          'type' => 'unknown',
          'label' => t('Generated password'),
        ),
      ),
    );
  return $actions;
}

/**
 * Action: Create custom user.
 */
function create_custom_user($login, $password,$email) {
  $fields = array(
    'name' => $login,
    'mail' => $email,
    'pass' => $password,
    'status' => 1,
    'init' => 'email address',
    'roles' => array(
      DRUPAL_AUTHENTICATED_RID => 'authenticated user',
    ),
  );
  $account = user_save('', $fields);
}

/**
 * Action: Generate a password.
 */
function add_password($length) {
  $passwd = user_password($length);
  return array('password_added' => $passwd);
}